# Generated by Django 3.1.4 on 2020-12-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spending',
            new_name='Transaction',
        ),
    ]
